"""AUTO-GENERATED from openapi.json by scripts/generate.py — DO NOT EDIT.

Spec version: 2026-07-16. Regenerate with: python scripts/generate.py
"""

from __future__ import annotations

API_VERSION = "2026-07-16"
DEFAULT_BASE_URL = "https://www.immersivecommons.com"

# operationId -> operation spec (method, path, query, scopes, auth, idempotency, sandbox)
OPERATIONS = {'listUpcomingEvents': {'operation_id': 'listUpcomingEvents',
                        'method': 'GET',
                        'path': '/api/events/upcoming',
                        'query': [{'name': 'limit', 'required': False}],
                        'scopes': ['events:read_upcoming'],
                        'requires_auth': False,
                        'bearer_reachable': True,
                        'browser_session': False,
                        'idempotent': False,
                        'has_body': False,
                        'sandbox': None,
                        'tags': ['events'],
                        'summary': 'List upcoming Immersive Commons events'},
 'getEventByLumaUrl': {'operation_id': 'getEventByLumaUrl',
                       'method': 'GET',
                       'path': '/api/events/get',
                       'query': [{'name': 'luma', 'required': True}],
                       'scopes': [],
                       'requires_auth': False,
                       'bearer_reachable': True,
                       'browser_session': False,
                       'idempotent': False,
                       'has_body': False,
                       'sandbox': None,
                       'tags': ['events'],
                       'summary': 'Look up a single event by its Luma URL'},
 'tailAgentEvents': {'operation_id': 'tailAgentEvents',
                     'method': 'GET',
                     'path': '/api/events/next',
                     'query': [{'name': 'since', 'required': False},
                               {'name': 'types', 'required': False},
                               {'name': 'limit', 'required': False}],
                     'scopes': [],
                     'requires_auth': True,
                     'bearer_reachable': False,
                     'browser_session': True,
                     'idempotent': False,
                     'has_body': False,
                     'sandbox': None,
                     'tags': ['events', 'browser-session'],
                     'summary': "Cursor-tail the caller's agentic event log"},
 'rsvpToEvent': {'operation_id': 'rsvpToEvent',
                 'method': 'POST',
                 'path': '/api/events/rsvp',
                 'query': [],
                 'scopes': ['events:rsvp'],
                 'requires_auth': True,
                 'bearer_reachable': True,
                 'browser_session': False,
                 'idempotent': True,
                 'has_body': True,
                 'sandbox': 'simulated',
                 'tags': ['events'],
                 'summary': 'Queue an RSVP to a Luma event'},
 'requestEvent': {'operation_id': 'requestEvent',
                  'method': 'POST',
                  'path': '/api/events/request',
                  'query': [],
                  'scopes': ['events:request'],
                  'requires_auth': True,
                  'bearer_reachable': True,
                  'browser_session': False,
                  'idempotent': True,
                  'has_body': True,
                  'sandbox': 'simulated',
                  'tags': ['events'],
                  'summary': 'Propose a member event (operator-approved)'},
 'searchDirectory': {'operation_id': 'searchDirectory',
                     'method': 'GET',
                     'path': '/api/directory/search',
                     'query': [{'name': 'q', 'required': False},
                               {'name': 'limit', 'required': False}],
                     'scopes': ['directory:search'],
                     'requires_auth': True,
                     'bearer_reachable': True,
                     'browser_session': False,
                     'idempotent': False,
                     'has_body': False,
                     'sandbox': None,
                     'tags': ['directory'],
                     'summary': 'Search the member directory'},
 'listResources': {'operation_id': 'listResources',
                   'method': 'GET',
                   'path': '/api/resources/list',
                   'query': [],
                   'scopes': ['resources:read'],
                   'requires_auth': True,
                   'bearer_reachable': True,
                   'browser_session': False,
                   'idempotent': False,
                   'has_body': False,
                   'sandbox': None,
                   'tags': ['resources'],
                   'summary': 'List bookable resources'},
 'bookResource': {'operation_id': 'bookResource',
                  'method': 'POST',
                  'path': '/api/resources/book',
                  'query': [],
                  'scopes': ['resources:book'],
                  'requires_auth': True,
                  'bearer_reachable': True,
                  'browser_session': False,
                  'idempotent': True,
                  'has_body': True,
                  'sandbox': 'simulated',
                  'tags': ['resources'],
                  'summary': 'Queue a resource booking'},
 'getMyActivity': {'operation_id': 'getMyActivity',
                   'method': 'GET',
                   'path': '/api/activity/me',
                   'query': [{'name': 'limit', 'required': False}],
                   'scopes': ['membership:read'],
                   'requires_auth': True,
                   'bearer_reachable': True,
                   'browser_session': False,
                   'idempotent': False,
                   'has_body': False,
                   'sandbox': None,
                   'tags': ['account'],
                   'summary': "Read the caller's own activity log"},
 'getMyLeaderboardStatus': {'operation_id': 'getMyLeaderboardStatus',
                            'method': 'GET',
                            'path': '/api/leaderboard/me',
                            'query': [],
                            'scopes': ['leaderboard:manage'],
                            'requires_auth': True,
                            'bearer_reachable': True,
                            'browser_session': False,
                            'idempotent': False,
                            'has_body': False,
                            'sandbox': None,
                            'tags': ['leaderboard'],
                            'summary': "Read the caller's commit-leaderboard state"},
 'setLeaderboardOptIn': {'operation_id': 'setLeaderboardOptIn',
                         'method': 'POST',
                         'path': '/api/leaderboard/optin',
                         'query': [],
                         'scopes': ['leaderboard:manage'],
                         'requires_auth': True,
                         'bearer_reachable': True,
                         'browser_session': False,
                         'idempotent': False,
                         'has_body': True,
                         'sandbox': 'simulated',
                         'tags': ['leaderboard'],
                         'summary': 'Toggle commit-leaderboard opt-in'},
 'askResearch': {'operation_id': 'askResearch',
                 'method': 'POST',
                 'path': '/api/research/ask',
                 'query': [],
                 'scopes': ['research:query'],
                 'requires_auth': True,
                 'bearer_reachable': True,
                 'browser_session': False,
                 'idempotent': False,
                 'has_body': True,
                 'sandbox': 'real',
                 'tags': ['research'],
                 'summary': 'Query the research RAG corpus'},
 'submitHighlightPending': {'operation_id': 'submitHighlightPending',
                            'method': 'POST',
                            'path': '/api/ingest/highlights/pending',
                            'query': [],
                            'scopes': ['events:submit_recap'],
                            'requires_auth': True,
                            'bearer_reachable': True,
                            'browser_session': False,
                            'idempotent': True,
                            'has_body': True,
                            'sandbox': 'simulated',
                            'tags': ['highlights'],
                            'summary': 'Submit a highlight to the moderation queue'},
 'submitFeedback': {'operation_id': 'submitFeedback',
                    'method': 'POST',
                    'path': '/api/agent/feedback',
                    'query': [],
                    'scopes': ['feedback:submit'],
                    'requires_auth': False,
                    'bearer_reachable': True,
                    'browser_session': False,
                    'idempotent': False,
                    'has_body': True,
                    'sandbox': 'real',
                    'tags': ['feedback'],
                    'summary': 'File feedback, a feature request, or a breakage report'},
 'revokeOwnToken': {'operation_id': 'revokeOwnToken',
                    'method': 'POST',
                    'path': '/api/agent/token/revoke',
                    'query': [],
                    'scopes': [],
                    'requires_auth': True,
                    'bearer_reachable': True,
                    'browser_session': False,
                    'idempotent': False,
                    'has_body': False,
                    'sandbox': 'real',
                    'tags': ['auth'],
                    'summary': 'Self-revoke the presenting token'},
 'setupCheck': {'operation_id': 'setupCheck',
                'method': 'GET',
                'path': '/api/agent/setup-check',
                'query': [],
                'scopes': [],
                'requires_auth': False,
                'bearer_reachable': True,
                'browser_session': False,
                'idempotent': False,
                'has_body': False,
                'sandbox': None,
                'tags': ['auth'],
                'summary': "Deterministic 'am I set up?' probe"},
 'startSignup': {'operation_id': 'startSignup',
                 'method': 'POST',
                 'path': '/api/agent/signup/start',
                 'query': [],
                 'scopes': [],
                 'requires_auth': False,
                 'bearer_reachable': True,
                 'browser_session': False,
                 'idempotent': False,
                 'has_body': True,
                 'sandbox': None,
                 'tags': ['auth'],
                 'summary': 'Begin the RFC 8628 device-code token mint'},
 'pollSignup': {'operation_id': 'pollSignup',
                'method': 'GET',
                'path': '/api/agent/signup/poll',
                'query': [{'name': 'device_code', 'required': False}],
                'scopes': [],
                'requires_auth': False,
                'bearer_reachable': True,
                'browser_session': False,
                'idempotent': False,
                'has_body': False,
                'sandbox': None,
                'tags': ['auth'],
                'summary': 'Poll a device-code grant for completion'},
 'getDonorWall': {'operation_id': 'getDonorWall',
                  'method': 'GET',
                  'path': '/api/floor10/donations',
                  'query': [{'name': 'limit', 'required': False}],
                  'scopes': [],
                  'requires_auth': False,
                  'bearer_reachable': True,
                  'browser_session': False,
                  'idempotent': False,
                  'has_body': False,
                  'sandbox': None,
                  'tags': ['payments'],
                  'summary': 'Read the public donor wall'},
 'getMyTier': {'operation_id': 'getMyTier',
               'method': 'GET',
               'path': '/api/tier/me',
               'query': [],
               'scopes': [],
               'requires_auth': True,
               'bearer_reachable': False,
               'browser_session': True,
               'idempotent': False,
               'has_body': False,
               'sandbox': None,
               'tags': ['membership', 'browser-session'],
               'summary': "Read the caller's membership tier"},
 'requestTier': {'operation_id': 'requestTier',
                 'method': 'POST',
                 'path': '/api/tier/request',
                 'query': [],
                 'scopes': [],
                 'requires_auth': True,
                 'bearer_reachable': False,
                 'browser_session': True,
                 'idempotent': False,
                 'has_body': True,
                 'sandbox': None,
                 'tags': ['membership', 'browser-session'],
                 'summary': 'Request a higher membership tier'},
 'cancelTierRequest': {'operation_id': 'cancelTierRequest',
                       'method': 'DELETE',
                       'path': '/api/tier/request',
                       'query': [],
                       'scopes': [],
                       'requires_auth': True,
                       'bearer_reachable': False,
                       'browser_session': True,
                       'idempotent': False,
                       'has_body': False,
                       'sandbox': None,
                       'tags': ['membership', 'browser-session'],
                       'summary': 'Cancel the pending tier request'}}
